-- Generated from auction_v2.sqlite by scripts/generate-supabase-sql-from-sqlite.js
create schema if not exists public;

create table if not exists public."admin_audit_logs" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "actor_id" text not null,
  "command_name" text not null,
  "summary" text not null,
  "target_summary" text,
  "channel_id" text,
  "created_at" bigint not null
);

create index if not exists "idx_admin_audit_logs_guild_time" on public."admin_audit_logs" ("guild_id", "created_at", "id");

create table if not exists public."command_usage_stats" (
  "guild_id" text not null,
  "command_name" text not null,
  "usage_count" bigint default 0 not null,
  "first_used_at" bigint not null,
  "last_used_at" bigint not null,
  primary key ("guild_id", "command_name")
);

create index if not exists "idx_command_usage_command" on public."command_usage_stats" ("command_name", "usage_count", "last_used_at");

create table if not exists public."disabled_global_manager_servers" (
  "guild_id" text not null primary key
);

create table if not exists public."fixture_settings" (
  "guild_id" text not null primary key,
  "min_players" text default '7v7',
  "max_players" text default '9v9',
  "max_reserve" bigint default 2,
  "rep_rules" text default '1 rep = 30 runs, 2 rep = 25 runs, 3 rep = 20 runs',
  "match_format" text default '20 Overs Elite with catch',
  "deadline" text,
  "title_text" text default 'Cinematic Showdown',
  "sponsor_text" text,
  "max_matches_per_day" bigint default 1,
  "auto_announce_time" text,
  "auto_announce_enabled" bigint default 0
);

create table if not exists public."fixture_setup_state" (
  "guild_id" text not null primary key,
  "step" text not null,
  "data" text not null,
  "timestamp" bigint not null
);

create table if not exists public."generated_fixtures" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "season_name" text not null,
  "day_number" bigint not null,
  "team_a_id" bigint not null,
  "team_b_id" bigint not null,
  "stadium_id" text,
  "status" text default 'PENDING',
  "group_letter" text default 'LEAGUE'
);

create table if not exists public."global_log_settings" (
  "id" bigint not null primary key,
  "channel_id" text
);

create table if not exists public."global_managers" (
  "user_id" text not null primary key
);

create table if not exists public."guild_settings" (
  "guild_id" text not null primary key,
  "timezone" text default 'UTC',
  "sales_log_channel_id" text,
  "schedule_season" text,
  "fixture_announcement_channel_id" text,
  "auction_stats_season" text,
  "team_name_change_limit" bigint default 2,
  "team_rename_window_open" bigint default 1,
  "regteam_command_channel_id" text,
  "community_roster_log_channel_id" text,
  "community_roster_manage_open" bigint default 1,
  "team_rename_window_expires_at" bigint,
  "auction_bid_timer_seconds" bigint default 15,
  "auction_call_timer_seconds" bigint default 2,
  "community_join_requests_open" bigint default 1,
  "admin_audit_log_channel_id" text,
  "admin_audit_logs_enabled" bigint default 1,
  "community_player_log_channel_id" text,
  "community_player_logs_enabled" bigint default 1,
  "stadium_channel_id" text,
  "ping_restricted_channel_id" text
);

create table if not exists public."hc_analysis_sessions" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "channel_id" text not null,
  "started_by" text not null,
  "note_text" text,
  "status" text default 'ACTIVE' not null,
  "started_at" bigint not null,
  "ended_at" bigint
);

create unique index if not exists "sqlite_autoindex_hc_analysis_sessions_1" on public."hc_analysis_sessions" ("guild_id", "channel_id", "status");

create table if not exists public."hc_auto_matches" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "channel_id" text not null,
  "status" text default 'ACTIVE' not null,
  "started_at" bigint not null,
  "updated_at" bigint not null,
  "ended_at" bigint,
  "finalized_at" bigint
);

create index if not exists "idx_hc_auto_matches_finalized_at" on public."hc_auto_matches" ("finalized_at", "ended_at");

create index if not exists "idx_hc_auto_matches_guild_channel_status" on public."hc_auto_matches" ("guild_id", "channel_id", "status", "updated_at");

create table if not exists public."hc_cricket_saved_embeds" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "source_channel_id" text not null,
  "source_message_id" text not null,
  "source_author_id" text not null,
  "embed_index" bigint default 0 not null,
  "embed_title" text,
  "embed_description" text,
  "embed_json" text not null,
  "source_created_at" bigint not null,
  "saved_by" text not null,
  "saved_at" bigint not null,
  "note_text" text
);

create unique index if not exists "sqlite_autoindex_hc_cricket_saved_embeds_1" on public."hc_cricket_saved_embeds" ("guild_id", "source_message_id", "embed_index");

create table if not exists public."hc_global_matchups" (
  "batter_norm" text not null,
  "bowler_norm" text not null,
  "batter_display_name" text not null,
  "bowler_display_name" text not null,
  "runs" bigint default 0 not null,
  "balls" bigint default 0 not null,
  "dismissals" bigint default 0 not null,
  "matches" bigint default 0 not null,
  "innings_faced" bigint default 0 not null,
  "updated_at" bigint not null,
  "faced_matches" bigint default 0 not null,
  primary key ("batter_norm", "bowler_norm")
);

create index if not exists "idx_hc_global_matchups_updated_at" on public."hc_global_matchups" ("updated_at");

create table if not exists public."ipl_prediction_matches" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "fixture_key" text not null,
  "fixture_number" bigint not null,
  "match_label" text not null,
  "team_a" text not null,
  "team_b" text not null,
  "match_date_label" text not null,
  "match_day_label" text,
  "match_time_label" text not null,
  "starts_at" bigint not null,
  "deadline_at" bigint not null,
  "announce_channel_id" text,
  "announce_message_id" text,
  "status" text default 'ANNOUNCED' not null,
  "winner_team" text,
  "announced_by" text,
  "announced_at" bigint not null,
  "settled_at" bigint
);

create index if not exists "idx_ipl_prediction_matches_guild_status_time" on public."ipl_prediction_matches" ("guild_id", "status", "starts_at");

create unique index if not exists "sqlite_autoindex_ipl_prediction_matches_1" on public."ipl_prediction_matches" ("guild_id", "fixture_key");

create table if not exists public."ipl_prediction_settings" (
  "guild_id" text not null primary key,
  "channel_id" text,
  "reminder_role_id" text,
  "reminder_panel_channel_id" text,
  "reminder_panel_message_id" text,
  "announcement_channel_id" text,
  "announcement_role_ids_json" text
);

create table if not exists public."ipl_top4_entries" (
  "guild_id" text not null,
  "user_id" text not null,
  "slot_1_team" text not null,
  "slot_2_team" text not null,
  "slot_3_team" text not null,
  "slot_4_team" text not null,
  "submitted_at" bigint not null,
  primary key ("guild_id", "user_id")
);

create index if not exists "idx_ipl_top4_entries_guild_user" on public."ipl_top4_entries" ("guild_id", "user_id");

create table if not exists public."ipl_top4_results" (
  "guild_id" text not null primary key,
  "slot_1_team" text not null,
  "slot_2_team" text not null,
  "slot_3_team" text not null,
  "slot_4_team" text not null,
  "settled_by" text not null,
  "settled_at" bigint not null
);

create table if not exists public."playoff_matches" (
  "id" bigint not null primary key,
  "guild_id" text not null,
  "season" bigint not null,
  "stage" text not null,
  "team_a" text not null,
  "score_a" text,
  "team_b" text not null,
  "score_b" text,
  "winner" text,
  "match_number" bigint,
  "timestamp" bigint not null
);

create table if not exists public."potd_polls" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "channel_id" text not null,
  "message_id" text not null,
  "season_name" text not null,
  "label_text" text not null,
  "option_count" bigint not null,
  "allow_multiple_votes" bigint default 0 not null,
  "created_at" bigint not null,
  "closes_at" bigint not null,
  "status" text default 'OPEN' not null,
  "result_message_id" text,
  "source_window_start_at" bigint,
  "source_window_end_at" bigint
);

create index if not exists "idx_potd_polls_window_lookup" on public."potd_polls" ("guild_id", "season_name", "label_text", "source_window_start_at", "source_window_end_at");

create index if not exists "idx_potd_polls_status_time" on public."potd_polls" ("status", "closes_at");

create unique index if not exists "sqlite_autoindex_potd_polls_1" on public."potd_polls" ("guild_id", "message_id");

create table if not exists public."potd_settings" (
  "guild_id" text not null primary key,
  "channel_id" text,
  "window_start_minute" bigint default 1200 not null,
  "window_end_minute" bigint default 180 not null,
  "window_end_day_offset" bigint default 1 not null,
  "allow_multiple_votes" bigint default 0 not null,
  "results_channel_id" text,
  "ping_role_id" text
);

create table if not exists public."pt_matches" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "season" bigint not null,
  "team_a" text not null,
  "score_a_runs" bigint not null,
  "score_a_wickets" bigint not null,
  "team_b" text not null,
  "score_b_runs" bigint not null,
  "score_b_wickets" bigint not null,
  "winner" text,
  "timestamp" bigint not null,
  "match_number" bigint default 0,
  "group_letter" text default 'LEAGUE'
);

create index if not exists "idx_pt_matches_guild_season" on public."pt_matches" ("guild_id", "season");

create table if not exists public."pt_settings" (
  "guild_id" text not null primary key,
  "current_season" bigint default 1,
  "layout_size" bigint default 10,
  "format_type" text default 'LEAGUE',
  "group_limit" text default 'A'
);

create table if not exists public."pt_team_aliases" (
  "guild_id" text not null,
  "full_name" text not null,
  "alias" text not null,
  primary key ("guild_id", "alias")
);

create table if not exists public."public_pings" (
  "guild_id" text not null,
  "role_id" text not null,
  "cooldown_seconds" bigint default 3600,
  "last_ping_timestamp" bigint default 0,
  "alias" text,
  "restricted_channel_id" text,
  primary key ("guild_id", "role_id")
);

create table if not exists public."reserve_limits" (
  "guild_id" text not null primary key,
  "limit_count" bigint default 2 not null
);

create table if not exists public."role_captains" (
  "guild_id" text not null,
  "role_id" text not null,
  "captain_id" text not null,
  primary key ("guild_id", "role_id")
);

create table if not exists public."role_pingers" (
  "guild_id" text not null,
  "role_id" text not null,
  "pinger_id" text not null,
  "command_name" text not null,
  primary key ("guild_id", "command_name")
);

create table if not exists public."scheduled_messages" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "target_role_id" text not null,
  "message_content" text not null,
  "scheduled_time" bigint not null,
  "status" text default 'PENDING' not null,
  "author_id" text not null,
  "target_type" text default 'ROLE'
);

create index if not exists "idx_sched_messages_status_time" on public."scheduled_messages" ("status", "scheduled_time");

create table if not exists public."sets" (
  "guild_id" text not null,
  "set_name" text not null,
  "base_price_lakhs" bigint not null,
  "increment_lakhs" bigint default 20 not null,
  "set_order" bigint,
  primary key ("guild_id", "set_name")
);

create index if not exists "idx_sets_guild_order" on public."sets" ("guild_id", "set_order", "set_name");

create table if not exists public."stats_match_context" (
  "guild_id" text not null,
  "match_id" text not null,
  "user_id" text not null,
  "season_name" text not null,
  "source_message_id" text not null,
  "source_channel_id" text,
  "match_timestamp" bigint not null,
  "team_id" bigint,
  "opponent_team_id" bigint,
  "team_name_snapshot" text,
  "opponent_name_snapshot" text,
  "fixture_day_number" bigint,
  primary key ("guild_id", "match_id", "user_id")
);

create index if not exists "idx_stats_match_context_window" on public."stats_match_context" ("guild_id", "season_name", "match_timestamp");

create table if not exists public."stats_matches" (
  "match_id" text not null,
  "guild_id" text not null,
  "season_name" text not null,
  "user_id" text not null,
  "runs" bigint default 0,
  "balls_played" bigint default 0,
  "runs_conceded" bigint default 0,
  "balls_bowled" bigint default 0,
  "wickets" bigint default 0,
  "not_out" bigint default 0,
  "match_mvp" double precision default 0,
  "timestamp" bigint not null,
  "message_id" text not null,
  "match_number" bigint default 0,
  primary key ("match_id", "user_id")
);

create table if not exists public."stats_players" (
  "guild_id" text not null,
  "season_name" text not null,
  "user_id" text not null,
  "runs" bigint default 0,
  "balls_played" bigint default 0,
  "runs_conceded" bigint default 0,
  "balls_bowled" bigint default 0,
  "wickets" bigint default 0,
  "not_out_count" bigint default 0,
  "innings_bat" bigint default 0,
  "innings_bowl" bigint default 0,
  "matches_played" bigint default 0,
  "fifties" bigint default 0,
  "hundreds" bigint default 0,
  "ducks" bigint default 0,
  "highscore" bigint default 0,
  "best_bowling_runs" bigint default 0,
  "best_bowling_wkts" bigint default 0,
  "three_fer" bigint default 0,
  "five_fer" bigint default 0,
  "total_mvp" double precision default 0,
  "thirties" bigint default 0,
  "runs_1_5" bigint default 0,
  "runs_6_9" bigint default 0,
  "low_sr_60" bigint default 0,
  "low_sr_80" bigint default 0,
  "zero_wkts_2overs" bigint default 0,
  "high_eco_18" bigint default 0,
  "high_eco_16" bigint default 0,
  "highscore_not_out" bigint default 0,
  primary key ("guild_id", "season_name", "user_id")
);

create index if not exists "idx_stats_players_guild_season" on public."stats_players" ("guild_id", "season_name");

create table if not exists public."stats_seasons" (
  "guild_id" text not null,
  "season_name" text not null,
  "is_active" bigint default 0,
  "season_num" bigint,
  "layout_size" bigint,
  "format_type" text,
  "group_limit" text,
  primary key ("guild_id", "season_name")
);

create table if not exists public."support_bug_reports" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "bug_number" bigint not null,
  "author_id" text not null,
  "channel_id" text,
  "message_id" text,
  "title" text not null,
  "description_text" text not null,
  "status" text default 'open' not null,
  "severity" text default 'medium' not null,
  "note_text" text,
  "created_at" bigint not null,
  "updated_at" bigint not null
);

create index if not exists "idx_support_bug_reports_guild_status" on public."support_bug_reports" ("guild_id", "status", "bug_number");

create unique index if not exists "sqlite_autoindex_support_bug_reports_1" on public."support_bug_reports" ("guild_id", "bug_number");

create table if not exists public."support_server_configs" (
  "guild_id" text not null primary key,
  "role_ids_json" text default '{}' not null,
  "channel_ids_json" text default '{}' not null,
  "panel_message_ids_json" text default '{}' not null,
  "log_channel_ids_json" text default '{}' not null,
  "misc_json" text default '{}' not null,
  "ticket_counter" bigint default 0 not null,
  "suggestion_counter" bigint default 0 not null,
  "bug_counter" bigint default 0 not null,
  "created_at" bigint not null,
  "updated_at" bigint not null
);

create table if not exists public."support_suggestions" (
  "id" bigint not null primary key,
  "guild_id" text not null,
  "suggestion_number" bigint not null,
  "author_id" text not null,
  "channel_id" text,
  "message_id" text,
  "content" text not null,
  "status" text default 'pending' not null,
  "note_text" text,
  "created_at" bigint not null,
  "updated_at" bigint not null
);

create index if not exists "idx_support_suggestions_guild_status" on public."support_suggestions" ("guild_id", "status", "suggestion_number");

create unique index if not exists "sqlite_autoindex_support_suggestions_1" on public."support_suggestions" ("guild_id", "suggestion_number");

create table if not exists public."support_tickets" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "ticket_number" bigint not null,
  "channel_id" text,
  "opener_id" text not null,
  "ticket_type" text not null,
  "status" text default 'OPEN' not null,
  "priority" text default 'medium' not null,
  "subject" text not null,
  "details_text" text not null,
  "claimed_by" text,
  "request_status" text,
  "internal_notes" text,
  "created_at" bigint not null,
  "updated_at" bigint not null,
  "closed_at" bigint,
  "closed_by" text,
  "transcript_message_id" text
);

create index if not exists "idx_support_tickets_channel" on public."support_tickets" ("channel_id");

create index if not exists "idx_support_tickets_guild_status" on public."support_tickets" ("guild_id", "status", "updated_at");

create unique index if not exists "sqlite_autoindex_support_tickets_2" on public."support_tickets" ("guild_id", "ticket_number");

create unique index if not exists "sqlite_autoindex_support_tickets_1" on public."support_tickets" ("channel_id");

create table if not exists public."support_warnings" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "user_id" text not null,
  "moderator_id" text not null,
  "reason_text" text not null,
  "created_at" bigint not null
);

create index if not exists "idx_support_warnings_guild_user" on public."support_warnings" ("guild_id", "user_id", "created_at");

create table if not exists public."team_groups" (
  "guild_id" text not null,
  "season_name" text not null,
  "team_id" bigint not null,
  "group_letter" text not null,
  primary key ("guild_id", "season_name", "team_id")
);

create table if not exists public."team_reservations" (
  "guild_id" text not null,
  "season_name" text not null,
  "team_id" bigint not null,
  "used_count" bigint default 0,
  primary key ("guild_id", "season_name", "team_id")
);

create table if not exists public."team_stadiums" (
  "guild_id" text not null,
  "team_id" bigint not null,
  "channel_id" text not null,
  "rename_count" bigint default 0,
  primary key ("guild_id", "team_id")
);

create table if not exists public."teams" (
  "guild_id" text not null,
  "team_id" bigint generated by default as identity not null primary key,
  "team_name" text not null,
  "owner_discord_id" text not null,
  "purse_lakhs" bigint not null,
  "max_roster_size" bigint default 15 not null,
  "role_id" text,
  "name_change_count" bigint default 0 not null
);

create unique index if not exists "sqlite_autoindex_teams_2" on public."teams" ("guild_id", "owner_discord_id");

create unique index if not exists "sqlite_autoindex_teams_1" on public."teams" ("guild_id", "team_name");

create unique index if not exists "uq_teams_guild_id_team_id" on public."teams" ("guild_id", "team_id");

create table if not exists public."trade_settings" (
  "guild_id" text not null primary key,
  "is_open" bigint default 0,
  "log_channel_id" text
);

create table if not exists public."trades" (
  "id" bigint not null primary key,
  "guild_id" text not null,
  "initiator_id" text not null,
  "target_owner_id" text not null,
  "player_a_id" bigint not null,
  "player_b_id" bigint not null,
  "status" text default 'PENDING',
  "created_at" bigint
);

create table if not exists public."auction_players" (
  "guild_id" text not null,
  "discord_id" text not null,
  "ign" text not null,
  "set_name" text,
  "status" text default 'AVAILABLE' not null,
  "sold_to_team_id" bigint,
  "sold_for_lakhs" bigint,
  primary key ("guild_id", "discord_id"),
  foreign key ("sold_to_team_id") references public."teams" ("team_id"),
  foreign key ("guild_id", "set_name") references public."sets" ("guild_id", "set_name")
);

create index if not exists "idx_auction_players_status_set" on public."auction_players" ("guild_id", "status", "set_name");

create table if not exists public."hc_analysis_messages" (
  "id" bigint generated by default as identity not null primary key,
  "session_id" bigint not null,
  "guild_id" text not null,
  "channel_id" text not null,
  "source_message_id" text not null,
  "source_author_id" text not null,
  "content_text" text,
  "embed_count" bigint default 0 not null,
  "payload_json" text not null,
  "source_created_at" bigint not null,
  "captured_at" bigint not null,
  foreign key ("session_id") references public."hc_analysis_sessions" ("id")
);

create unique index if not exists "sqlite_autoindex_hc_analysis_messages_1" on public."hc_analysis_messages" ("session_id", "source_message_id");

create table if not exists public."hc_auto_message_versions" (
  "id" bigint generated by default as identity not null primary key,
  "match_id" bigint not null,
  "guild_id" text not null,
  "channel_id" text not null,
  "source_message_id" text not null,
  "source_author_id" text not null,
  "content_text" text,
  "embed_count" bigint default 0 not null,
  "payload_json" text not null,
  "payload_hash" text not null,
  "source_created_at" bigint not null,
  "observed_at" bigint not null,
  "event_type" text not null,
  foreign key ("match_id") references public."hc_auto_matches" ("id") on delete cascade
);

create index if not exists "idx_hc_auto_message_versions_guild_channel" on public."hc_auto_message_versions" ("guild_id", "channel_id", "observed_at");

create index if not exists "idx_hc_auto_message_versions_match_time" on public."hc_auto_message_versions" ("match_id", "observed_at", "id");

create unique index if not exists "sqlite_autoindex_hc_auto_message_versions_1" on public."hc_auto_message_versions" ("match_id", "source_message_id", "payload_hash");

create table if not exists public."hc_matchup_match_log" (
  "id" bigint generated by default as identity not null primary key,
  "match_id" bigint not null,
  "guild_id" text not null,
  "channel_id" text not null,
  "batter_norm" text not null,
  "bowler_norm" text not null,
  "batter_display_name" text not null,
  "bowler_display_name" text not null,
  "runs" bigint default 0 not null,
  "balls" bigint default 0 not null,
  "dismissals" bigint default 0 not null,
  "matches" bigint default 1 not null,
  "innings_faced" bigint default 0 not null,
  "created_at" bigint not null,
  "faced_matches" bigint default 0 not null,
  foreign key ("match_id") references public."hc_auto_matches" ("id") on delete cascade
);

create index if not exists "idx_hc_matchup_match_log_match" on public."hc_matchup_match_log" ("match_id");

create index if not exists "idx_hc_matchup_match_log_pair" on public."hc_matchup_match_log" ("batter_norm", "bowler_norm", "created_at");

create unique index if not exists "sqlite_autoindex_hc_matchup_match_log_1" on public."hc_matchup_match_log" ("match_id", "batter_norm", "bowler_norm");

create table if not exists public."ipl_prediction_entries" (
  "match_id" bigint not null,
  "user_id" text not null,
  "predicted_team" text not null,
  "predicted_at" bigint not null,
  primary key ("match_id", "user_id"),
  foreign key ("match_id") references public."ipl_prediction_matches" ("id") on delete cascade
);

create index if not exists "idx_ipl_prediction_entries_match_team" on public."ipl_prediction_entries" ("match_id", "predicted_team");

create table if not exists public."ipl_prediction_panels" (
  "match_id" bigint not null,
  "user_id" text not null,
  "prompt_message_id" text not null,
  "updated_at" bigint not null,
  primary key ("match_id", "user_id"),
  foreign key ("match_id") references public."ipl_prediction_matches" ("id") on delete cascade
);

create index if not exists "idx_ipl_prediction_panels_match_user" on public."ipl_prediction_panels" ("match_id", "user_id");

create table if not exists public."match_reservations" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "team_a_id" bigint not null,
  "team_b_id" bigint not null,
  "reserved_by_captain_id" text not null,
  "status" text default 'PENDING' not null,
  "scheduled_time" bigint,
  "created_at" bigint not null,
  "agreement_time" text,
  "stadium_channel_id" text,
  "season_name" text,
  "reserve_day_number" bigint,
  "fixture_day_number" text,
  "reserve_team_id" bigint,
  foreign key ("team_b_id") references public."teams" ("team_id"),
  foreign key ("team_a_id") references public."teams" ("team_id")
);

create index if not exists "idx_match_res_status_time" on public."match_reservations" ("status", "scheduled_time");

create table if not exists public."potd_poll_candidates" (
  "poll_id" bigint not null,
  "option_rank" bigint not null,
  "user_id" text not null,
  "match_id" text not null,
  "runs" bigint default 0,
  "balls_played" bigint default 0,
  "wickets" bigint default 0,
  "runs_conceded" bigint default 0,
  "balls_bowled" bigint default 0,
  "match_mvp" double precision default 0,
  "team_name_snapshot" text,
  "opponent_name_snapshot" text,
  "fixture_day_number" bigint,
  primary key ("poll_id", "option_rank"),
  foreign key ("poll_id") references public."potd_polls" ("id") on delete cascade
);

create index if not exists "idx_potd_poll_candidates_poll_rank" on public."potd_poll_candidates" ("poll_id", "option_rank");

create table if not exists public."support_ticket_members" (
  "ticket_id" bigint not null,
  "user_id" text not null,
  "added_by" text,
  "added_at" bigint not null,
  primary key ("ticket_id", "user_id"),
  foreign key ("ticket_id") references public."support_tickets" ("id") on delete cascade
);

create table if not exists public."team_captains" (
  "guild_id" text not null,
  "team_id" bigint not null,
  "captain_discord_id" text not null,
  primary key ("guild_id", "team_id"),
  foreign key ("guild_id", "team_id") references public."teams" ("guild_id", "team_id")
);

create table if not exists public."team_join_requests" (
  "id" bigint generated by default as identity not null primary key,
  "guild_id" text not null,
  "team_id" bigint not null,
  "requester_id" text not null,
  "status" text default 'PENDING' not null,
  "note" text,
  "created_at" bigint not null,
  "responder_id" text,
  "responded_at" bigint,
  foreign key ("team_id") references public."teams" ("team_id")
);

create table if not exists public."team_vice_captains" (
  "guild_id" text not null,
  "team_id" bigint not null,
  "vice_captain_discord_id" text not null,
  primary key ("guild_id", "team_id"),
  foreign key ("guild_id", "team_id") references public."teams" ("guild_id", "team_id")
);

create table if not exists public."auction_ledger" (
  "guild_id" text not null primary key,
  "player_id" text not null,
  "current_bid_lakhs" bigint not null,
  "current_holder_team_id" bigint,
  foreign key ("current_holder_team_id") references public."teams" ("team_id"),
  foreign key ("guild_id", "player_id") references public."auction_players" ("guild_id", "discord_id")
);